export const TYPES = {
  Application: Symbol.for('Application'),
  Bot: Symbol.for('Bot'),
  ILogger: Symbol.for('LoggerService'),
  IUsersService: Symbol.for('UsersService'),
  IOrderService: Symbol.for('OrderService'),
  IUsersRepository: Symbol.for('UsersRepository'),
  CurrencyRepository: Symbol.for('CurrencyRepository'),
  IOrderRepository: Symbol.for('OrderRepository'),
  PrismaService: Symbol.for('PrismaService'),
  MakeOrderScene: Symbol.for('MakeOrderScene'),
  UsersScene: Symbol.for('UsersScene'),
  OrdersScene: Symbol.for('OrdersScene'),
  CurrencyService: Symbol.for('CurrencyService'),
};
